provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-cv-ml:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-cv-ml:0.2.0
    environment:
      exec_timeout: 120
      write_timeout: 120
      read_timeout: 120
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
