provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-cv-hal:
    lang: dockerfile
    handler: ./fn-cv-hal
    image: disarm/fn-cv-hal:0.0.1
    environment:
      exec_timeout: 120
      write_timeout: 120
      read_timeout: 120
      combine_output: false
      # write_debug: true
