provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-cv-ml:
    lang: dockerfile
    handler: ./fn-cv-ml
    image: disarm/fn-cv-ml:0.0.4
    environment:
      exec_timeout: 120
      write_timeout: 120
      read_timeout: 120
      combine_output: false
      # write_debug: true
